# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: KIZWeb
description: >- # this means to ignore newlines until "baseurl:"
  Adapted from Bay. Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://kizzhang.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research Insterest
    - name: Projects

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: zzhang578-c@my.cityu.edu.hk
      link: mailto:zzhang578-c@my.cityu.edu.hk
    - name: WeChat
      value: alavagarde
      link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/kizzhang
      username: "@kizzhang"
    - name: LinkedIn
      link: http://linkedin.com/in/
    - name: GitHub
      link: http://github.com/kizzhang

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
